### ISSUE TITLE
Add Brick Wall background

### ISSUE THREAD

**Issue by JollyJolli** [JollyJolli/HacktoberWall#75]
Hey there! I really like the page as it is right know, but i would like to make the back part of the cards like a wall texture 

![image](https://github.com/user-attachments/assets/2225e484-2e90-46b2-ae67-71b4fb176c3b)

And maybe make the names as a grafitti, it would be really cool.

## Tasks
- [ ] Wall Background
- [ ] Graffitis Names

**Comment by lirena00** [comment]
so like instead of green bg it should be something like this? 
![image](https://github.com/user-attachments/assets/e3e52bf3-e805-431c-afc3-974785c32511)
and font perhaps like this?
https://fonts.google.com/specimen/Sedgwick+Ave
or 
https://fonts.google.com/specimen/Calligraffitti

you can assign the issue to me I will do it

**Comment by JollyJolli** [comment]
You really got what I want to do!

**Comment by JollyJolli** [comment]
Happy contributing and thank you!

**Comment by lirena00** [comment]
this issue should be closed now since #79 has been merged
